# Generated by Django 4.2 on 2024-01-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=255)),
                ('complemento', models.CharField(blank=True, max_length=255)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=255)),
                ('disponivel', models.BooleanField(default=True)),
                ('foto', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
